create table daily_macro_structure (
    as_of_date date not null,
    macro_state text not null,
    spy_trend_z double precision,
    vix_z double precision,
    hy_oas_z double precision,
    macro_trend_factor double precision,
    macro_volatility_factor double precision,
    macro_credit_risk_factor double precision,
    macro_trend_strength double precision,
    macro_risk_pressure double precision,
    data_version text,
    run_id text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    primary key (as_of_date)
);

create table daily_sector_structure (
    as_of_date date not null,
    sector_name text not null,
    sector_etf text,
    sector_state text not null,
    rs_z double precision,
    rs_momentum_z double precision,
    breadth_frac double precision,
    breadth_momentum double precision,
    vol_ratio_z double precision,
    vol_trend_z double precision,
    sector_relative_strength_factor double precision,
    sector_breadth_factor double precision,
    sector_participation_factor double precision,
    sector_momentum_factor double precision,
    sector_support_score double precision,
    sector_breadth_health double precision,
    sector_momentum double precision,
    data_version text,
    run_id text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    primary key (as_of_date, sector_name)
);

create table daily_symbol_structure (
    as_of_date date not null,
    symbol text not null,
    symbol_state text not null,
    ma20 double precision,
    ma50 double precision,
    ma20_slope double precision,
    ma50_slope double precision,
    atr_pct double precision,
    volume_ratio double precision,
    range_position_short double precision,
    range_position_mid double precision,
    distance_to_high_short double precision,
    distance_to_high_mid double precision,
    symbol_trend_factor double precision,
    symbol_trend_slope_factor double precision,
    symbol_volatility_factor double precision,
    symbol_liquidity_factor double precision,
    symbol_position_factor_short double precision,
    symbol_position_factor_mid double precision,
    symbol_range_position_factor_short double precision,
    symbol_range_position_factor_mid double precision,
    symbol_trend_strength double precision,
    symbol_trend_slope double precision,
    symbol_volatility_state double precision,
    symbol_liquidity_quality double precision,
    symbol_position_quality_short double precision,
    symbol_position_quality_mid double precision,
    symbol_range_position_short double precision,
    symbol_range_position_mid double precision,
    symbol_reversal_pressure double precision,
    symbol_exhaustion_risk double precision,
    symbol_failure_risk double precision,
    data_version text,
    run_id text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    primary key (as_of_date, symbol)
);

create table daily_structure_runs (
    run_id text primary key,
    start_date date not null,
    end_date date not null,
    status text not null,
    symbols text[],
    sectors text[],
    started_at timestamptz default now(),
    finished_at timestamptz,
    error_message text
);